name: Step 0, Welcome

on: 
  push:
    branches:
      - main
  workflow_dispatch: 

permissions: 
  contents: write

jobs: 
  get_current_step:
    name: Check current step number
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v4
      - id: get_step
        run: |
          echo "current_step=$(cat ./.github/steps/-step.txt)" >> $GITHUB_OUTPUT
    outputs:
      current_step: ${{ steps.get_step.outputs.current_step }}

  on_start:
    name: On start
    needs: get_current_step
    if: >-
      ${{ !github.event.repository.is_template && needs.get_current_step.outputs.current_step == 0 }}
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v4
        with: 
          fetch-depth: 0
      - name: Update to step 1
        uses: skills/action-update-step@v2
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}
          from_step: 0
          to_step: 1

      # after being created from the template repository.
      - name: Initialize repository
        run: ./.github/script/initialize-repository.sh --dry-run=false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


